// Production-safe subset of seed.ts: only the real Infinito 2K26 event
// catalog (19 events + Athletics 2K26 sub-options), extracted verbatim from
// seed.ts's "5B. INFINITO 2K26 EVENT CATALOG" section.
//
// Deliberately excludes everything else seed.ts creates — Users (dev
// fixtures with a public, hardcoded password), the old demo
// Football/BGMI/Athletics events, Brand, CaTask, Teams, Registrations,
// Payments, Credentials — none of that belongs in a real production
// database. Idempotent (upsert on a fixed id), safe to re-run.
//
// Run: npx ts-node prisma/seed-events-prod.ts

import {
  PrismaClient,
  Prisma,
  BroadCategory,
  EventRegistrationType,
  GenderCategory,
  FeeStructure,
  SubOptionType,
} from '@prisma/client';
import 'dotenv/config';

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const IDS = {
  eventCricket:          'b0000000-0000-4000-8000-000000000004',
  eventFootball2k26:     'b0000000-0000-4000-8000-000000000005',
  eventBasketball:       'b0000000-0000-4000-8000-000000000006',
  eventBadmintonBoys:    'b0000000-0000-4000-8000-000000000007',
  eventBadmintonWomen:   'b0000000-0000-4000-8000-000000000008',
  eventLawnTennisBoys:   'b0000000-0000-4000-8000-000000000009',
  eventLawnTennisGirls:  'b0000000-0000-4000-8000-000000000010',
  eventMrInfinito:       'b0000000-0000-4000-8000-000000000011',
  eventTableTennisBoys:  'b0000000-0000-4000-8000-000000000012',
  eventTableTennisGirls: 'b0000000-0000-4000-8000-000000000013',
  eventSquashBoys:       'b0000000-0000-4000-8000-000000000014',
  eventSquashGirls:      'b0000000-0000-4000-8000-000000000015',
  eventVolleyballMen:    'b0000000-0000-4000-8000-000000000016',
  eventVolleyballWomen:  'b0000000-0000-4000-8000-000000000017',
  eventChess:            'b0000000-0000-4000-8000-000000000018',
  eventPowerlifting:     'b0000000-0000-4000-8000-000000000019',
  eventAthletics2k26:    'b0000000-0000-4000-8000-000000000020',
  eventKabaddiBoys:      'b0000000-0000-4000-8000-000000000021',
  eventKabaddiGirls:     'b0000000-0000-4000-8000-000000000022',

  subOpt200m:        'c0000000-0000-4000-8000-000000000003',
  subOpt400m:        'c0000000-0000-4000-8000-000000000004',
  subOpt800m:        'c0000000-0000-4000-8000-000000000005',
  subOpt1500m:       'c0000000-0000-4000-8000-000000000006',
  subOpt5000m:       'c0000000-0000-4000-8000-000000000007',
  subOptLongJump:    'c0000000-0000-4000-8000-000000000008',
  subOptDiscusThrow: 'c0000000-0000-4000-8000-000000000009',
  subOptShotPut:     'c0000000-0000-4000-8000-000000000010',
  subOpt100mV2:      'c0000000-0000-4000-8000-000000000011',
  subOpt4x100V2:     'c0000000-0000-4000-8000-000000000012',
  subOpt4x400V2:     'c0000000-0000-4000-8000-000000000013',
  subOpt4x100Mixed:  'c0000000-0000-4000-8000-000000000014',
};

async function upsertById<T>(
  model: { upsert: (args: any) => Promise<T> },
  id: string,
  data: object,
): Promise<T> {
  return model.upsert({
    where: { id },
    update: {},
    create: { id, ...data },
  });
}

async function main() {
  console.log('\n🎪  Seeding Infinito 2K26 event catalog (19 events) — production\n');

  const STANDARD_ACCOMMODATION_RATE = 490.0; // Rs 250/day stay + Rs 240/day food, per head

  const infinito2k26Events: { id: string; data: Prisma.EventCreateInput }[] = [
    {
      id: IDS.eventCricket,
      data: {
        name: 'Cricket 2K26',
        slug: 'cricket-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Cricket',
        description: '11-a-side cricket tournament, open registration.',
        pointOfContactName: 'Ankit Singh / K Ayush / Akshay Kumar',
        pointOfContactPhone: '9508830291',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.OPEN,
        teamSizeMin: 11,
        teamSizeMax: 16,
        maxSubstitutes: 5,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 6500.0,
        startDate: new Date('2026-09-15T08:00:00Z'),
        venue: 'IIT Patna Cricket Ground',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 50000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventFootball2k26,
      data: {
        name: 'Football 2K26',
        slug: 'football-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Football',
        description: '11-a-side football tournament. One team roster per gender bracket.',
        pointOfContactName: 'Chandra Mohan / Devyansh / Ishaan',
        pointOfContactPhone: '7849892436',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.OPEN,
        teamSizeMin: 11,
        teamSizeMax: 16,
        maxSubstitutes: 5,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.GENDER_BASED,
        feeMale: 6500.0,
        feeFemale: 3000.0,
        startDate: new Date('2026-09-15T08:00:00Z'),
        venue: 'IIT Patna Football Ground',
        hasAccommodation: true,
        accommodationRate: 490.0,
        prizePool: 30000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventBasketball,
      data: {
        name: 'Basketball 2K26',
        slug: 'basketball-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Basketball',
        description: '5-a-side basketball tournament. One team roster per gender bracket.',
        pointOfContactName: 'Piyush Kumar / Priyam',
        pointOfContactPhone: '8000101831',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.OPEN,
        teamSizeMin: 5,
        teamSizeMax: 12,
        maxSubstitutes: 7,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.GENDER_BASED,
        feeMale: 4800.0,
        feeFemale: 4200.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Basketball Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 25000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventBadmintonBoys,
      data: {
        name: 'Badminton Boys 2K26',
        slug: 'badminton-boys-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Badminton',
        description: "Men's team badminton tournament.",
        pointOfContactName: 'Vijendra / Parth / Kunal',
        pointOfContactPhone: '8239919115',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.MEN,
        teamSizeMin: 5,
        teamSizeMax: 5,
        maxSubstitutes: 0,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 2500.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Badminton Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 20000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventBadmintonWomen,
      data: {
        name: "Badminton Women's 2K26",
        slug: 'badminton-womens-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Badminton',
        description: "Women's team badminton tournament.",
        pointOfContactName: 'Vijendra / Parth / Kunal',
        pointOfContactPhone: '8239919115',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.WOMEN,
        teamSizeMin: 3,
        teamSizeMax: 3,
        maxSubstitutes: 0,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 1500.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Badminton Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 15000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventLawnTennisBoys,
      data: {
        name: 'Lawn Tennis Boys 2K26',
        slug: 'lawn-tennis-boys-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Lawn Tennis',
        description: "Men's doubles/pair-based lawn tennis tournament.",
        pointOfContactName: 'Himanshu Shekhar C / Raunak',
        pointOfContactPhone: '9108238522',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.MEN,
        teamSizeMin: 2,
        teamSizeMax: 4,
        maxSubstitutes: 2,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 1000.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Lawn Tennis Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 8000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventLawnTennisGirls,
      data: {
        name: 'Lawn Tennis Girls 2K26',
        slug: 'lawn-tennis-girls-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Lawn Tennis',
        description: "Women's doubles/pair-based lawn tennis tournament.",
        pointOfContactName: 'Himanshu Shekhar C / Raunak',
        pointOfContactPhone: '9108238522',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.WOMEN,
        teamSizeMin: 2,
        teamSizeMax: 4,
        maxSubstitutes: 2,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 800.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Lawn Tennis Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 6000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventMrInfinito,
      data: {
        name: 'Mr. Infinito 2K26',
        slug: 'mr-infinito-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Body Show',
        description: 'Individual body show competition.',
        registrationType: EventRegistrationType.INDIVIDUAL,
        genderCategory: GenderCategory.MEN,
        viceCaptainRequired: false,
        coachAllowed: false,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 599.0,
        startDate: new Date('2026-10-05T10:00:00Z'),
        venue: 'IIT Patna Gymkhana',
        hasAccommodation: false,
        isPublished: true,
        registrationOpen: true,
        customFieldsDef: [
          { label: 'Roll No.', inputType: 'TEXT', required: true, scope: 'TEAM' },
          { label: 'College ID', inputType: 'TEXT', required: true, scope: 'TEAM' },
        ],
      },
    },
    {
      id: IDS.eventTableTennisBoys,
      data: {
        name: 'Table Tennis Boys 2K26',
        slug: 'table-tennis-boys-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Table Tennis',
        description: "Men's team table tennis tournament. Bring your own kit.",
        pointOfContactName: 'Akshat Agrawal / Shreya Yadav',
        pointOfContactPhone: '7905554877',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.MEN,
        teamSizeMin: 2,
        teamSizeMax: 4,
        maxSubstitutes: 2,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 1500.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Indoor Sports Complex',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 15000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventTableTennisGirls,
      data: {
        name: 'Table Tennis Girls 2K26',
        slug: 'table-tennis-girls-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Table Tennis',
        description: "Women's team table tennis tournament. Bring your own kit.",
        pointOfContactName: 'Akshat Agrawal / Shreya Yadav',
        pointOfContactPhone: '7905554877',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.WOMEN,
        teamSizeMin: 2,
        teamSizeMax: 3,
        maxSubstitutes: 1,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 1000.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Indoor Sports Complex',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 10000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventSquashBoys,
      data: {
        name: 'Squash Boys 2K26',
        slug: 'squash-boys-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Squash',
        description: "Men's team squash tournament.",
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.MEN,
        teamSizeMin: 3,
        teamSizeMax: 4,
        maxSubstitutes: 1,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 800.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Squash Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 8000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventSquashGirls,
      data: {
        name: 'Squash Girls 2K26',
        slug: 'squash-girls-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Squash',
        description: "Women's team squash tournament.",
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.WOMEN,
        teamSizeMin: 3,
        teamSizeMax: 4,
        maxSubstitutes: 1,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 600.0,
        startDate: new Date('2026-09-16T08:00:00Z'),
        venue: 'IIT Patna Squash Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 5000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventVolleyballMen,
      data: {
        name: 'Volleyball Men 2K26',
        slug: 'volleyball-men-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Volleyball',
        description: "Men's team volleyball tournament.",
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.MEN,
        teamSizeMin: 5,
        teamSizeMax: 11,
        maxSubstitutes: 6,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 4800.0,
        startDate: new Date('2026-09-17T08:00:00Z'),
        venue: 'IIT Patna Volleyball Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 25000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventVolleyballWomen,
      data: {
        name: "Volleyball Women's 2K26",
        slug: 'volleyball-womens-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Volleyball',
        description: "Women's team volleyball tournament.",
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.WOMEN,
        teamSizeMin: 6,
        teamSizeMax: 12,
        maxSubstitutes: 6,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 4500.0,
        startDate: new Date('2026-09-17T08:00:00Z'),
        venue: 'IIT Patna Volleyball Court',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 15000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventChess,
      data: {
        name: 'Chess 2K26',
        slug: 'chess-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Chess',
        description: 'Team chess tournament, per-head registration fee.',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.OPEN,
        teamSizeMin: 4,
        teamSizeMax: 6,
        maxSubstitutes: 0,
        viceCaptainRequired: false,
        coachAllowed: false,
        feeStructure: FeeStructure.PER_HEAD,
        feePerHead: 249.0,
        startDate: new Date('2026-09-15T09:00:00Z'),
        venue: 'IIT Patna Indoor Sports Complex',
        hasAccommodation: false,
        prizePool: 5000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventPowerlifting,
      data: {
        name: 'Powerlifting 2K26',
        slug: 'powerlifting-2k26',
        broadCategory: BroadCategory.INDOOR,
        sportCategory: 'Powerlifting',
        description: 'Small-team powerlifting competition.',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.OPEN,
        teamSizeMin: 1,
        teamSizeMax: 3,
        maxSubstitutes: 0,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 999.0,
        startDate: new Date('2026-09-16T09:00:00Z'),
        venue: 'IIT Patna Gymkhana',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 10000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventAthletics2k26,
      data: {
        name: 'Athletics 2K26 (Track & Field)',
        slug: 'athletics-2k26-track-field',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Athletics',
        description:
          'Individual track and field registration. Select up to 3 individual disciplines ' +
          'and up to 2 relay disciplines; one flat fee covers the full selection.',
        pointOfContactName: 'Prince / Aayush Aryan',
        pointOfContactPhone: '9506122970',
        registrationType: EventRegistrationType.INDIVIDUAL,
        genderCategory: GenderCategory.OPEN,
        viceCaptainRequired: false,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 700.0,
        startDate: new Date('2026-09-16T07:00:00Z'),
        venue: 'IIT Patna Athletic Track',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 50000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventKabaddiBoys,
      data: {
        name: 'Kabaddi Boys 2K26',
        slug: 'kabaddi-boys-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Kabaddi',
        description: "Men's team kabaddi tournament.",
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.MEN,
        teamSizeMin: 7,
        teamSizeMax: 11,
        maxSubstitutes: 4,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 4000.0,
        startDate: new Date('2026-09-17T08:00:00Z'),
        venue: 'IIT Patna Kabaddi Ground',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 25000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
    {
      id: IDS.eventKabaddiGirls,
      data: {
        name: 'Kabaddi Girls 2K26',
        slug: 'kabaddi-girls-2k26',
        broadCategory: BroadCategory.OUTDOOR,
        sportCategory: 'Kabaddi',
        description:
          "Women's team kabaddi tournament. Unlike the men's bracket, one substitute " +
          'is mandatory — reflected here as a higher teamSizeMin rather than a special flag.',
        registrationType: EventRegistrationType.TEAM,
        genderCategory: GenderCategory.WOMEN,
        teamSizeMin: 8,
        teamSizeMax: 12,
        maxSubstitutes: 4,
        viceCaptainRequired: true,
        coachAllowed: true,
        feeStructure: FeeStructure.FLAT,
        feeFlat: 2000.0,
        startDate: new Date('2026-09-17T08:00:00Z'),
        venue: 'IIT Patna Kabaddi Ground',
        hasAccommodation: true,
        accommodationRate: STANDARD_ACCOMMODATION_RATE,
        prizePool: 10000.0,
        isPublished: true,
        registrationOpen: true,
      },
    },
  ];

  for (const { id, data } of infinito2k26Events) {
    await upsertById(prisma.event, id, data);
  }

  console.log(`   ✅  ${infinito2k26Events.length} Infinito 2K26 events created.\n`);

  console.log('🏃  Seeding Athletics 2K26 EventSubOptions...');

  const individualDisciplines: { id: string; name: string }[] = [
    { id: IDS.subOpt100mV2, name: '100m' },
    { id: IDS.subOpt200m, name: '200m' },
    { id: IDS.subOpt400m, name: '400m' },
    { id: IDS.subOpt800m, name: '800m' },
    { id: IDS.subOpt1500m, name: '1500m' },
    { id: IDS.subOpt5000m, name: '5000m' },
    { id: IDS.subOptLongJump, name: 'Long Jump' },
    { id: IDS.subOptDiscusThrow, name: 'Discus Throw' },
    { id: IDS.subOptShotPut, name: 'Shot Put' },
  ];

  for (const discipline of individualDisciplines) {
    await upsertById(prisma.eventSubOption, discipline.id, {
      eventId: IDS.eventAthletics2k26,
      name: discipline.name,
      type: SubOptionType.INDIVIDUAL,
      maxSelectionsPerReg: 3,
      isActive: true,
    });
  }

  const relayDisciplines: { id: string; name: string }[] = [
    { id: IDS.subOpt4x100V2, name: '4×100m Relay' },
    { id: IDS.subOpt4x400V2, name: '4×400m Relay (Boys)' },
    { id: IDS.subOpt4x100Mixed, name: '4×100m Mixed Relay' },
  ];

  for (const relay of relayDisciplines) {
    await upsertById(prisma.eventSubOption, relay.id, {
      eventId: IDS.eventAthletics2k26,
      name: relay.name,
      type: SubOptionType.RELAY,
      maxSelectionsPerReg: 2,
      isActive: true,
    });
  }

  console.log(
    `   ✅  ${individualDisciplines.length} individual + ${relayDisciplines.length} relay Athletics 2K26 sub-options created.\n`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
